### ISSUE TITLE
Add support for AWS Session Manager

### ISSUE THREAD

**Issue by pavloos** [claranet/ssha#70]
Session Manager allows connections to  instances in private and public subnets without going through bastions. This would also allow connections to Windows instances. 
awscli supports that with  [session-manager-plugin](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html), also [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ssm.html#SSM.Client.start_session) has been updated 

```
$ aws ssm start-session --target i-1234567890abcdefg --region eu-west-1
Starting session with SessionId: xxxxxxxxxxxx

sh-4.2$ hostname
ip-10-0-1-167.eu-west-1.compute.internal
```

**Comment by raymondbutcher** [comment]
Done in 5a6bad06497ac9f36fc420ebffac82431a47db79
